# Generated by Django 4.1.2 on 2022-10-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('MOTORS', 'Motors'), ('ELECTRONICS', 'Electronics'), ('COLLECTIBLES_ART', 'Collectibles & Art'), ('CLOTHING_ACC', 'Clothing & Accessories'), ('BUSINESS_IND', 'Business & Industrial'), ('HOME_GARDEN', 'Home & Garden'), ('SPORTING', 'Sporting Goods'), ('JEWELRY', 'Jewelry & Watches'), ('OTHER', 'Other')], default='MOTORS', max_length=16),
        ),
    ]
