# Generated by Django 4.1.2 on 2022-10-19 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.ImageField(default='No Image', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
