# Generated by Django 4.1.2 on 2022-10-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('MS', 'Motors'), ('ECCS', 'Electronics'), ('C_ART', 'Collectibles & Art'), ('CLOTH', 'Clothing & Accessories'), ('BUSS', 'Business & Industrial'), ('HG', 'Home & Garden'), ('SPORT', 'Sporting Goods'), ('JE', 'Jewelry & Watches'), ('OT', 'Other')], default='MOTORS', max_length=16),
        ),
    ]
