# Generated by Django 4.1.2 on 2022-10-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_image_alter_listings_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(default='No Image', upload_to='images'),
        ),
    ]
