# Generated by Django 4.1.2 on 2022-10-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user',
            new_name='user_id',
        ),
    ]
